export const STORE_EVENTS = "STORE_EVENTS";
export const OPEN_DETAILS = "OPEN_DETAILS";
export const STORE_SCROLL_POSITION = "STORE_SCROLL_POSITION";
export const SET_LOADING = "SET_LOADING";
export const SET_USER_ROLE = "SET_USER_ROLE";

